# Form implementation generated from reading ui file 'LED_UI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(837, 642)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(580, 160, 251, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ON = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        font.setBold(True)
        self.ON.setFont(font)
        self.ON.setObjectName("ON")
        self.verticalLayout.addWidget(self.ON)
        self.OFF = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        font.setBold(True)
        self.OFF.setFont(font)
        self.OFF.setObjectName("OFF")
        self.verticalLayout.addWidget(self.OFF)
        self.Toggle = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        font.setBold(True)
        self.Toggle.setFont(font)
        self.Toggle.setObjectName("Toggle")
        self.verticalLayout.addWidget(self.Toggle)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 180, 441, 221))
        self.label_2.setObjectName("label_2")
        self.brightness_controller = QtWidgets.QSlider(parent=Dialog)
        self.brightness_controller.setGeometry(QtCore.QRect(20, 550, 539, 15))
        self.brightness_controller.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.brightness_controller.setObjectName("brightness_controller")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(120, 420, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 341, 161))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 101, 101))
        self.label.setStyleSheet("/* 灭灯状态：深灰渐变 */\n"
"background: qradialgradient(cx:0.5, cy:0.5, radius:0.5,\n"
"                            fx:0.5, fy:0.5,\n"
"                            stop:0 #888888,\n"
"                            stop:1 #444444);\n"
"border-radius: 20px;\n"
"border: 1px solid #666666;\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(170, 70, 151, 31))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ON.setText(_translate("Dialog", "ON"))
        self.OFF.setText(_translate("Dialog", "OFF"))
        self.Toggle.setText(_translate("Dialog", "Toggle"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:700;\">Come on控个灯吧</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">亮度：0.00</span></p></body></html>"))
        self.groupBox.setTitle(_translate("Dialog", "GPIO State"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">state</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">目标引脚电平状态</span></p></body></html>"))
